---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wanzinyazar/mlops.git
    targetRevision: HEAD
    path: ml_ops
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    name: argo-workflows
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: '0.17.1'
    chart: argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  labels:
    name: argo-events
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: '2.0.4'
    chart: argo-events
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
  
    
      

      